### ISSUE TITLE
Questions around RSSAC002v3 specification

### ISSUE THREAD

**Issue by jelu** [DNS-OARC/dnscap#152]
This issue was created here on request by @wessels to be able to include other RSSAC members in the discussion.

**Please include the question number when commenting in this thread.**

## 1. Undocumented change from v2 to v3

Section 2 for v2 says:
```
Only syntactically correct DNS messages should be counted. Data-less connections and
invalid, malformed, short, or non-DNS messages should not be counted.
```

But v3 changed to:
```
Only syntactically correct DNS messages should be counted. Data-less connections or
non-DNS messages should not be counted.
```

Is it correctly assumed that invalid, malformed and cut-off DNS messages should be counted?  (Could not find this mentioned in 9.3)

Additional comments can be found here: https://github.com/DNS-OARC/dnscap/issues/91

## 2. `start-period`

Why is the value of `start-period` quoted with single quotes?  There is really no need for that in YAML afaik.

## 3. `traffic-volume` and `unique-sources` metric

It is not clear if zero counts should be included or not (minor issue, I know, but the specification disregards other zero counts).

## 4. `traffic-sizes` metric

It is not clear what to do with empty buckets, should they be included or discarded?

## 5. Multiple YAML documents in the same file

It is possible to have multiple YAML documents in the same file (separated by `---`), have you considered this?  This will be the output way for the RSSM plugin with optional scripts to split it up into the 5.7 URL Path Standard.

**Comment by wessels** [comment]
(1) As I tried to say in #91, "Only syntactically correct DNS messages should be counted." If that means that the RSSM plugin needs to call a (ldns) parsing function to check message correctness, then so be it.  You could make it a runtime option if you're worried about performance.

(2) I assume you're pointing out that the example YAML files have the start-period value quoted.  Thats probably because the software used to generate the examples chose to quote them.  If quotes are not required per the spec then feel free to omit them.

(3) Sorry the spec is not clear.  I would expect a consumer of the YAML file to be fine if zero-count items were omitted.  However, since traffic-volume and unique-sources have a relatively small number of counters, and since I think it is rare to have zero counts in these metrics, my recommendation would be to always include the zero-count items so that it is clear that there were indeed zero counts for that period and the items weren't simply accidentally omitted from the output.

(4) 5.4 says "Only size ranges with nonzero counts shall be listed."

(5) It probably was considered at some point but since the specification uses separate files I don't see that changing any time soon.

**Comment by jelu** [comment]
@wessels 
4. that is not what I asked about, what if the either bucket/hash is empty?
5. currently the output and merge script handles multiple YAML documents in a single file, is that OK or should the output be split?

**Comment by wessels** [comment]
On (4), sorry I'm still not following you.  RSSAC002 uses the term bucket when describing the traffic-sizes metric.  As I see it, bucket corresponds to size range.  So I'm not sure what an empty bucket could mean other than a size range with zero counts.   RSSAC002 doesn't use the term hash, and the rssm source code doesn't use hash tables for traffic-sizes so I'm not sure what you mean by that either.

On (5) As I understand the expected mode of operation for dnscap/rssm is to have it output many files per day, which will then be merged.  I think its fine to output a single file for now.  If someone needs multiple YAML file output from rssm directly it can be future development.

**Comment by jelu** [comment]
@wessels 
4. I mean the YAML output, for example if the example in the specification was:
```
---
version: rssac002v3
service: a.root-servers.net
start-period: '2016-01-01T00:00:00Z'
metric: traffic-sizes
udp-request-sizes:
  16-31: 12345
udp-response-sizes:
  16-31: 12345
tcp-request-sizes:
tcp-response-sizes:
```
Should `tcp-request-sizes` and `tcp-response-sizes` (or any of the buckets/YAML hashes) be included when empty?

**Comment by jelu** [comment]
@wessels ping 4. Should `tcp-request-sizes` and `tcp-response-sizes` (or any of the buckets/YAML hashes) be included when empty?

**Comment by wessels** [comment]
Since RSSAC002 doesn't provide any guidance, I think you could implement whatever you prefer.  In my opinion it would be preferable to print it like this:
```
---
version: rssac002v3
service: a.root-servers.net
start-period: '2018-02-01T00:00:00Z'
metric: traffic-sizes
udp-request-sizes:
udp-response-sizes:
tcp-request-sizes:
tcp-response-sizes:
```
so that the data consumer has some extra confidence that the file wasn't truncated due to some bug.

**Comment by jelu** [comment]
@wessels The plugin outputs `udp-request-sizes: {}` for empty hashes/buckets which is according to YAML specification, is that OK?

**Comment by wessels** [comment]
Okay with me...

**Comment by jelu** [comment]
OK, then the issues are solved. It was my hope that these could be considered for the next version of the specification but maybe that's a bit too much of a challenge.
