### ISSUE TITLE
github page for dnscap gives out-of-date location for libbind

### ISSUE THREAD

**Issue by vixie** [DNS-OARC/dnscap#190]
according to the ISC web site that the libbind reference links to today: "At present, NetBSD maintains libbind code, now known as “netresolv”.For more information, visit http://wiki.netbsd.org/individual-software-releases/netresolv/". it might be better for the dnscap page to point directly to the netbsd page.

**Comment by jelu** [comment]
Updated to the ISC ftp URL because the NetBSD page doesn't say how to download their `libbind`. They also say that it will be removed and replaced by `netresolv` but nothing has been done for years so seems it's abandoned. If someone needs to be done on `dnscap` side then I think it would be better to remove the dependency of `libbind` then to support `netresolv`.
